### ISSUE TITLE
`repo init` conflict with ChromiumOS

### ISSUE THREAD

**Issue by dysinger** [coreos/scripts#153]
I've reproduced this on clean machines of Ubuntu 12.04.3

Scenario #1 (Success):
Build CoreOS or ChromiumOS by itself.

Senario #2 (Fail):
1) Build CoreOS (Success!)
2) Try to repo init for ChromiumOS (GPG validation fail)

Scenario #3 (Fail):
1) Build ChromiumOS (Success!)
2) Try to repo init for CoreOS (GPG validation fail).

**Comment by marineam** [comment]
Use of depot_tools was dropped from our docs a while ago, replacing it with the default repo upstream Android's docs recommend. Hopefully that is less likely to get things mixed up.
