### ISSUE TITLE
build_image error at end of build

### ISSUE THREAD

**Issue by stresler** [coreos/scripts#429]
Currently when setting up the SDK, the final build_image command builds an image, but then issues an error at the end of the output.  

https://gist.github.com/stresler/68faf57554a2e7a721c2 has the output.

**Comment by stresler** [comment]
It looks like the build is generated but it stops before it makes the symlinks to beta_latest (or stable_latest or ehathave you). 

stresler@001cd109:~/coreos/src/build/images/amd64-usr$ ls -la
total 16
drwxr-xr-x 4 stresler stresler 4096 Jul  2 12:37 .
drwxr-xr-x 3 stresler stresler 4096 Jul  2 12:26 ..
drwxr-xr-x 3 stresler stresler 4096 Jul  2 12:29 beta-730.0.0+2015-07-02-1225-a1
stresler@001cd109:~/coreos/src/build/images/amd64-usr$ ls -la beta-730.0.0+2015-07-02-1237-a1/
total 755732
drwxr-xr-x 3 stresler stresler       4096 Jul  2 12:40 .
drwxr-xr-x 4 stresler stresler       4096 Jul  2 12:37 ..
-rw-r--r-- 1 stresler stresler 4756340736 Jul  2 12:40 coreos_production_image.bin
-rw-r--r-- 1 stresler stresler     748067 Jul  2 12:40 coreos_production_image_contents.txt
-rw-r--r-- 1 stresler stresler       7113 Jul  2 12:40 coreos_production_image_licenses.txt
-rw-r--r-- 1 stresler stresler       5934 Jul  2 12:40 coreos_production_image_packages.txt
-rw-r--r-- 1 stresler stresler         65 Jul  2 12:40 coreos_production_image_verity.txt
-rw-r--r-- 1 stresler stresler 1073741824 Jul  2 12:40 coreos_production_update.bin
-rw-r--r-- 1 stresler stresler         84 Jul  2 12:37 developer_data
-rw-r--r-- 1 stresler stresler     102214 Jul  2 12:40 doc.tar.bz2
drwxr-xr-x 2 root     root           4096 Jul  2 12:37 rootfs
stresler@001cd109:~/coreos/src/build/images/amd64-usr$

**Comment by marineam** [comment]
This was caused by a bad build of update_engine the SDK. The latest version 731 should be good but any existing SDK that pulled in the bad build will need to re-install the update_engine package:

    sudo emerge update_engine

After that all should be good.
